name: Linting
on: 
  push:
    branches:
      - "main"
  pull_request:

jobs:
  linting:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: "Install rubocop"
      run: "gem install rubocop"
    - name: "Run rubocop"
      run: "rubocop"